### ISSUE TITLE
Support for pie chart labels

### ISSUE THREAD

**Issue by ppershing** [martinsik/google-chart-generator#2]
It would be nice if one can set the "labels" option of PieChart.

**Comment by martinsik** [comment]
Hey, pie charts do have label now:

```php
$chart = new PieChart(['width' => '150px', 'height' => '150px', 'pieHole' => 0.5]);
$chart->addData([new SingleData(40, 'Arc #1'), new SingleData(60, 'Arc #2'), new SingleData(80, 'Arc #3')]);

```

See [pie chart test scenarios](https://github.com/martinsik/google-chart-generator/blob/master/features/bootstrap/PieChartContext.php#L37).
