### ISSUE TITLE
Default colors change

### ISSUE THREAD

**Issue by ppershing** [martinsik/google-chart-generator#3]
I like the default colors, but the combination of yellow with orange is quite hard to distinguish and these two colors are both in the first five default colors. Maybe aqua or other color would be better as an default.

**Comment by martinsik** [comment]
Hi, should be fixed or easily customized by setting colors:
```php
$options = ['color' => '#005500', 'lineDashStyle' => [5, 2], 'pointSize' => 3, 'lineWidth' => 1];
$chart->addData(new SequenceData([2 => 14, 3 => 19, 4 => 12, 5 => 17, 6 => 13], $options));
```

See example in [one of the test scenarios](https://github.com/martinsik/google-chart-generator/blob/master/features/bootstrap/LineChartContext.php#L36).
